- name: pull latest docker images for monitoring stack
  command: "docker pull {{ item }}"
  loop:
    - grafana/loki:latest
    - grafana/grafana:latest
    - prom/prometheus:latest
  register: docker_pull_result

- name: determine whether a restart is required of the docker stack
  set_fact:
    docker_restart_required: true
  when: item.stdout is search('Downloaded newer image')
  loop: "{{ docker_pull_result.results }}"

- name: Tear down existing monitoring stack
  community.docker.docker_compose_v2:
    project_src: "{{ monitor_user_dir }}/docker"
    state: absent
  when: docker_restart_required is defined
  become: true
  become_user: "{{ monitor_user }}"

- name: Start monitoring stack
  community.docker.docker_compose_v2:
    project_src: "{{ monitor_user_dir }}/docker"
    state: present
  when: docker_restart_required is defined
  become: true
  become_user: "{{ monitor_user }}"

- name: Prune unused docker images
  command: "docker image prune -a --force"
  when: docker_restart_required is defined
