- name: pull latest docker images for arrr stack
  community.docker.docker_image:
    name: "{{ item.image }}"
    source: pull
    force_source: true
  loop: "{{ arrr_stack_services }}"
  register: docker_pull_result
  become: true

- name: Restart systemd services for updated images
  systemd:
    name: "{{ item.item.service }}"
    state: restarted
  loop: "{{ docker_pull_result.results }}"
  when: item.changed
  become: true

- name: Prune unused docker images
  command: "docker image prune --force"
  # verification: run prune if any image was updated
  when: docker_pull_result.changed
  become: true
