- name: Deploy calibre service systemd service file
  template:
    src: calibre.service.j2
    dest: "/etc/systemd/system/calibre.service"
    owner: root
    group: root
    mode: '0644'
  notify: restart calibre
  become: true

- name: Enable and start calibre service
  systemd:
    name: calibre.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true
