- name: Deploy calibre-web service systemd service file
  template:
    src: calibre-web.service.j2
    dest: "/etc/systemd/system/calibre-web.service"
    owner: root
    group: root
    mode: '0644'
  notify: restart calibre-web
  become: true

- name: Enable and start calibre-web service
  systemd:
    name: calibre-web.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true
