- name: Deploy lidarr service systemd service file
  template:
    src: lidarr.service.j2
    dest: "/etc/systemd/system/lidarr.service"
    owner: root
    group: root
    mode: '0644'
  notify: restart lidarr
  become: true

- name: Enable and start lidarr service
  systemd:
    name: lidarr.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true
