- name: Install dockerized traefik
  import_tasks: traefik.yml
  become: true

- name: Ensure group "{{ svc_user }}" exists with correct gid
  ansible.builtin.group:
    name: "{{ svc_user }}"
    state: present
    gid: "{{ svc_uid }}"
  become: true

- name: Create service user
  user:
    name: "{{ svc_user }}"
    password: '*'   # pw is locked/disabled.  key auth only + passwordless sudo
    state: present
    shell: /bin/bash
    createhome: yes
    home: "/home/{{ svc_user }}"
    uid: "{{ svc_uid }}"
    group: "{{ svc_user }}"
    groups:
      - docker
    append: true
  become: true

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ svc_user }}"
    group: "{{ svc_user }}"
    mode: "0750"
  loop:
    - "/home/{{ svc_user }}/space"
    - "/home/{{ svc_user }}/space/DO_NOT_USE"
    - "/home/{{ svc_user }}/space/downloads"
    - "/home/{{ svc_user }}/space/downloads/temp" # should be SSD
    - "/home/{{ svc_user }}/space/downloads/books"
    - "/home/{{ svc_user }}/space/downloads/music"
    - "/home/{{ svc_user }}/space/transcode"      # should be SSD
    - "/home/{{ svc_user }}/space/media"
    - "/home/{{ svc_user }}/space/media/movies"
    - "/home/{{ svc_user }}/space/media/tv"
    - "/home/{{ svc_user }}/space/media/books"
    - "/home/{{ svc_user }}/space/media/music"
    - "/home/{{ svc_user }}/plex"
    - "/home/{{ svc_user }}/plex/config"
    - "/home/{{ svc_user }}/radarr"
    - "/home/{{ svc_user }}/radarr/config"
    - "/home/{{ svc_user }}/readarr"
    - "/home/{{ svc_user }}/readarr/config"
    - "/home/{{ svc_user }}/calibre"
    - "/home/{{ svc_user }}/calibre/config"
    - "/home/{{ svc_user }}/calibre-web"
    - "/home/{{ svc_user }}/calibre-web/config"
    - "/home/{{ svc_user }}/sonarr"
    - "/home/{{ svc_user }}/sonarr/config"
    - "/home/{{ svc_user }}/prowlarr"
    - "/home/{{ svc_user }}/prowlarr/config"
    - "/home/{{ svc_user }}/sabnzbd/"
    - "/home/{{ svc_user }}/sabnzbd/config"
    - "/home/{{ svc_user }}/qbittorrent/"
    - "/home/{{ svc_user }}/qbittorrent/config"
    - "/home/{{ svc_user }}/qbittorrent/config/config"
    - "/home/{{ svc_user }}/transmission/"
    - "/home/{{ svc_user }}/transmission/config"
    - "/home/{{ svc_user }}/deluge"
    - "/home/{{ svc_user }}/deluge/config"
    - "/home/{{ svc_user }}/wireguard"
    - "/home/{{ svc_user }}/wireguard/config"
    - "/home/{{ svc_user }}/lidarr"
    - "/home/{{ svc_user }}/lidarr/config"
    - "/home/{{ svc_user }}/jackett"
    - "/home/{{ svc_user }}/jackett/config"
  become: true

- name: Create DO_NOT_USE file
  copy:
    src: "DO_NOT_USE"
    dest: "/home/{{ svc_user }}/space/DO_NOT_USE"
    owner: "{{ svc_user }}"
    group: "{{ svc_user }}"
    mode: "0750"
  become: true
  become_user: "{{ svc_user }}"

- name: Create docker network for stack
  community.docker.docker_network:
    name: proxy
    driver_options: { "com.docker.network.driver.mtu": "{{ sdn_mtu }}" }
  become: true

- name: Deploy wireguard
  import_tasks: wireguard.yml

- name: Deploy radarr
  import_tasks: radarr.yml

- name: Deploy readarr
  import_tasks: readarr.yml

- name: Deploy calibre
  import_tasks: calibre.yml

- name: Deploy calibre-web
  import_tasks: calibre-web.yml

- name: Deploy sonarr
  import_tasks: sonarr.yml

- name: Deploy prowlarr
  import_tasks: prowlarr.yml

#- name: Deploy sabnzbd
#  import_tasks: sabnzbd.yml

#- name: Deploy qbittorrent
#  import_tasks: qbittorrent.yml

- name: Deploy deluge
  import_tasks: deluge.yml

- name: Deploy plex
  import_tasks: plex.yml

- name: Deploy transmission
  import_tasks: transmission.yml

- name: Deploy lidarr
  import_tasks: lidarr.yml  

- name: Deploy jackett
  import_tasks: jackett.yml

