- name: Deploy plex service systemd service file
  template:
    src: plex.service.j2
    dest: "/etc/systemd/system/plex.service"
    owner: root
    group: root
    mode: '0644'
  notify: restart plex
  become: true

- name: Enable and start plex service
  systemd:
    name: plex.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true