- name: Deploy prowlarr service systemd service file
  template:
    src: prowlarr.service.j2
    dest: "/etc/systemd/system/prowlarr.service"
    owner: root
    group: root
    mode: '0644'
  notify: restart prowlarr
  become: true

- name: Enable and start prowlarr service
  systemd:
    name: prowlarr.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true