- name: Deploy qbittorrent configuration
  template:
    src: qbittorrent.conf.j2
    dest: "/home/{{ svc_user }}/qbittorrent/config/config/qBittorrent.conf"
    owner: "{{ svc_user }}"
    group: "{{ svc_user }}"
    mode: "0640"
  become: true
  become_user: "{{ svc_user }}"

- name: Deploy qbittorrent service systemd service file
  template:
    src: qbittorrent.service.j2
    dest: "/etc/systemd/system/qbittorrent.service"
    owner: root
    group: root
    mode: '0644'
  notify: restart qbittorrent
  become: true

- name: Enable and start qbittorrent service
  systemd:
    name: qbittorrent.service
    enabled: yes
    state: stopped  # temp disabled
    daemon_reload: yes
  become: true