- name: Deploy radarr service systemd service file
  template:
    src: radarr.service.j2
    dest: "/etc/systemd/system/radarr.service"
    owner: root
    group: root
    mode: '0644'
  notify: restart radarr
  become: true

- name: Enable and start radarr service
  systemd:
    name: radarr.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true
