- name: Deploy readarr service systemd service file
  template:
    src: readarr.service.j2
    dest: "/etc/systemd/system/readarr.service"
    owner: root
    group: root
    mode: '0644'
  notify: restart readarr
  become: true

- name: Enable and start readarr service
  systemd:
    name: readarr.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true
