- name: Deploy sonarr service systemd service file
  template:
    src: sonarr.service.j2
    dest: "/etc/systemd/system/sonarr.service"
    owner: root
    group: root
    mode: '0644'
  notify: restart sonarr
  become: true

- name: Enable and start sonarr service
  systemd:
    name: sonarr.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true
