- name: Create traefik service user
  user:
    name: "traefik"
    password: '*'   # pw is locked/disabled.  key auth only
    state: present
    shell: /bin/bash
    createhome: yes
    home: "/home/traefik"
    groups:
      - docker

- name: Create Traefik data directory
  file:
    path: "/home/traefik/data"
    state: directory
    owner: "traefik"
    group: "traefik"
    mode: "0750"

- name: Touch Traefik acme.json
  file:
    path: "/home/traefik/data/acme.json"
    state: touch
    owner: "traefik"
    group: "traefik"
    mode: "0600"

- name: Deploy traefik service systemd service file
  template:
    src: traefik.service.j2
    dest: /etc/systemd/system/traefik.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - daemon-reload
    - restart traefik

- name: Deploy traefik env file
  template:
    src: traefik.env.j2
    dest: /home/traefik/.traefik.env
    owner: traefik
    group: traefik
    mode: '0600'
  become: true
  notify:
    - restart traefik

- name: Deploy traefik.yml
  template:
    src: traefik.yml.j2
    dest: "/home/traefik/traefik.yml"
    owner: traefik
    group: traefik
    mode: '0640'
  notify: restart traefik

- name: Enable and start traefik ingress service
  become: true
  systemd:
    name: traefik.service
    enabled: yes
    state: started
    daemon_reload: yes
