#- name: Deploy transmission configuration
#  template:
#    src: transmission.conf.j2
#    dest: "/home/{{ svc_user }}/transmission/config/config/transmission.conf"
#    owner: "{{ svc_user }}"
#    group: "{{ svc_user }}"
#    mode: "0640"
#  become: true
#  become_user: "{{ svc_user }}"

- name: Deploy transmission service systemd service file
  template:
    src: transmission.service.j2
    dest: "/etc/systemd/system/transmission.service"
    owner: root
    group: root
    mode: '0644'
  notify: restart transmission
  become: true

- name: Enable and start transmission service
  systemd:
    name: transmission.service
    enabled: yes
    state: started  
    daemon_reload: yes
  become: true