- name: Deploy wireguard config file
  template:
    src: wg0.conf.j2.encrypted
    dest: "/home/{{ svc_user }}/wireguard/config/wg0.conf"
    owner: "{{ svc_user }}"
    group: "{{ svc_user }}"
    mode: "0600"
  become: true
  become_user: "{{ svc_user }}"

- name: Deploy wireguard service systemd service file
  template:
    src: wireguard.service.j2
    dest: "/etc/systemd/system/wireguard.service"
    owner: root
    group: root
    mode: '0644'
  #notify: restart wireguard
  # note: notify fails, FAILED! => {"changed": false, "msg": "Could not find the requested service wg-quick@wg0: host"}
  # has to do with some weirdness between systemd and docker. fix later :)
  become: true

- name: Enable and start wireguard service
  systemd:
    name: wireguard.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true