- name: Enumerate installed rust
  shell: ". /home/{{ svc_user }}/.cargo/env; rustc --version"
  ignore_errors: true
  register: rust_version

- name: Debug rust_version
  debug:
    msg: "{{ rust_version.stdout }}"

- name: Download rustup installer
  when: rust_version is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: install rust/cargo
  when: rust_version is failed
  shell: /tmp/sh.rustup.rs -y
