- name: Install dependencies
  include_tasks: install_deps.yml

- name: Install from source
  block:
    - name: Clone repo
      git:
        repo: '{{ stacks_repo }}'
        dest: '/home/{{ svc_user }}/stacks-blockchain'
        version: '{{ stacks_version }}'
        update: yes
        force: yes
        depth: 1
      
    - name: Build and install stacks
      command: '{{ item }}'
      args:
        chdir: '/home/{{ svc_user }}/stacks-blockchain'
      with_items:
        - 'cargo build --release --features monitoring_prom'
      environment:
        PATH: '/home/{{ svc_user }}/.cargo/bin::/usr/local/bin:/usr/bin:/bin:'

  become: true
  become_user: "{{ svc_user }}"

