- name: Check if rust is installed
  command: rustc --version
  environment:
    PATH: "/home/{{ svc_user }}/.cargo/bin"
  register: rust_check
  failed_when: false
  changed_when: false
  become: true
  become_user: "{{ svc_user }}"

- name: Debug rust_check
  debug:
    msg: "{{ rust_check }}"

- name : Install Rust
  block:
  - name: Install Rust
    shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    args:
      creates: /home/{{ svc_user }}/.cargo/env  # only run if rust not already installed
    become: true
    become_user: "{{ svc_user }}"
  when: rust_check.rc != 0

- name: Update Rust to latest version
  command: rustup update
  environment:
    PATH: "/home/{{ svc_user }}/.cargo/bin"
  become: true
  become_user: "{{ svc_user }}"
  when: rust_check.rc == 0
