- name: Deploy keystore generation script
  template:
    src: generate_keystore.sh.j2
    dest: "/home/{{ celo_user }}/generate_keystore.sh"
    owner: "{{ celo_user }}"
    group: "{{ celo_user }}"
    mode: '0750'

- name: Write keystore privkey to file
  shell: "echo {{ attestation_key }} > {{ celo_data_dir }}/attestation_signer_key"

- name: Set perms on privkey file
  shell: chmod 600 {{ celo_data_dir }}/attestation_signer_key && chown {{ celo_user }}:{{ celo_user }} {{ celo_data_dir }}/attestation_signer_key

- name: Write keystore password to file
  shell: "echo {{ attestation_signer_password }} > {{ celo_data_dir }}/attestation_signer_password"

- name: Set perms on privkey file
  shell: chmod 600 {{ celo_data_dir }}/attestation_signer_password && chown {{ celo_user }}:{{ celo_user }} {{ celo_data_dir }}/attestation_signer_password

- name: Generate keystore
  command: "/home/{{ celo_user }}/generate_keystore.sh"
  become: true
  become_user: "{{ celo_user }}"

- name: Remove artifacts used to generate keystore
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ celo_data_dir }}/attestation_signer_key"
    - "{{ celo_data_dir }}/attestation_signer_password"