- name: Main
  hosts: '{{ target }}'
  #gather_facts: false
  #vars_files:
  #  - '{{ var_file }}'
  #  - '{{ encrypted_var_file }}'
  roles:
    - role: proxmox_hypervisor
      tags: 'proxmox_hypervisor'
      become: true
    - role: base_server
      tags: 'base_server'
      become: true
    - role: dnsmasq_dhcp_server
      tags: 'dnsmasq'
      become: true
    - role: docker_server
      tags: 'docker_server'
      become: true
    - role: celo_attestation_server
      tags: 'celo_attestation_server'
      become: true
    - role: celo_proxy_server
      tags: 'celo_proxy_server'
      become: true
    - role: celo_validator_server
      tags: 'celo_validator_server'
      become: true
    - role: ingress_server
      tags: 'ingress_server'
      become: true
    - role: monitor_server
      tags: 'monitor_server'
      become: true
    - role: monitor_client
      tags: 'monitor_client'
      become: true
    - role: bitwarden_server
      tags: 'bitwarden_server'
      become: true    
    
  handlers:
      - name: restart sshd
        service:
          name: sshd
          state: restarted
        become: true
      
      - name: restart networking
        command: '/usr/sbin/ifreload -a'
        become: true

      - name: reload iptables
        shell: "/usr/sbin/iptables-restore < /etc/iptables.conf"
        become: true
      
      - name: reload ip6tables
        shell: "/usr/sbin/ip6tables-restore < /etc/ip6tables.conf"
        become: true

      - name: restart rsyslog
        service:
          name: rsyslog
          state: restarted
        become: true
      
      - name: restart wireguard
        service:
          name: wg-quick@wg0
          state: restarted
        become: true
      
      - name: restart dnsmasq
        service:
          name: dnsmasq
          state: restarted
        become: true
      
      - name: daemon-reload
        command: systemctl daemon-reload
        become: true
      
      - name: restart attestation
        service:
          name: celo-attestation
          state: restarted
        become: true
      
      - name: restart traefik
        service:
          name: traefik
          state: restarted
        become: true
      
      - name: restart docker
        service:
          name: docker
          state: restarted
        become: true

      - name: restart haproxy
        service:
          name: haproxy
          state: restarted
        become: true

      - name: restart bitwarden
        systemd:
          name: bitwarden
          daemon_reload: yes
          state: restarted
        become: true
      
      - name: restart celo-geth
        systemd:
          name: celo-geth
          daemon_reload: yes
          state: restarted
        become: true