- name: Main
  hosts: '{{ target }}'
  gather_facts: false
  #vars_files:
  #  - '{{ var_file }}'
  #  - '{{ encrypted_var_file }}'
  roles:
    - role: proxmox_hypervisor
      tags: 'proxmox_hypervisor'
    - role: generic_server
      tags: 'generic_server'
      become: true
    - role: dnsmasq_dhcp_server
      tags: 'dnsmasq'
    - role: docker_server
      tags: 'docker_server'
      become: true
    - role: celo_attestation_server
      tags: 'celo_attestation_server'
      become: true
    - role: ingress_server
      tags: 'ingress_server'
      become: true
    - role: bastion_server
      tags: 'bastion_server'
      become: true
    
  handlers:
      - name: restart sshd
        service:
          name: sshd
          state: restarted
        become: true
      
      - name: restart networking
        command: '/usr/sbin/ifreload -a'

      - name: reload iptables
        shell: "/usr/sbin/iptables-restore < /etc/iptables.conf"
      
      - name: reload ip6tables
        shell: "/usr/sbin/ip6tables-restore < /etc/ip6tables.conf"

      - name: restart rsyslog
        service:
          name: rsyslog
          state: restarted
      
      - name: restart wireguard
        service:
          name: wg-quick@wg0
          state: restarted
      
      - name: restart dnsmasq
        service:
          name: dnsmasq
          state: restarted
      
      - name: daemon-reload
        command: systemctl daemon-reload
        become: true
      
      - name: restart attestation
        service:
          name: celo-attestation
          state: restarted
        become: true
      
      - name: restart traefik
        service:
          name: traefik
          state: restarted
        become: true
