- name: Main
  hosts: '{{ target }}'
  #gather_facts: false
  vars_files:
    - '{{ var_file }}'
  roles:
    #- proxmox_hardening
    #- create_users
    - configure_storage
  handlers:
      - name: restart sshd
        service:
          name: sshd
          state: restarted

      - name: restart networking
        service:
          name: networking
          state: restarted

      - name: reload iptables
        shell: "/usr/sbin/iptables-restore < /etc/iptables.conf"
      
      - name: reload ip6tables
        shell: "/usr/sbin/ip6tables-restore < /etc/ip6tables.conf"

      - name: restart rsyslog
        service:
          name: rsyslog
          state: restarted
      
      - name: restart wireguard
        service:
          name: wg-quick@wg0
          state: restarted
