---
- name: download mevboost binary
  get_url:
    url: '{{ mevboost_binary }}'
    checksum: 'sha256:{{ mevboost_checksum }}'
    dest: '/home/{{ ethereum_user }}/downloads/mevboost_binary.tar.gz'
    mode: '0644'

- name: unarchive mevboost binary file
  unarchive:
    src: '/home/{{ ethereum_user }}/downloads/mevboost_binary.tar.gz'
    dest: '/home/{{ ethereum_user }}/downloads/mevboost/'
    mode: '0755'
    remote_src: true

- name: Copy mevboost binary
  copy:
    remote_src: true
    src: '/home/{{ ethereum_user }}/downloads/mevboost/mev-boost'
    dest: '/home/{{ ethereum_user }}/bin/mev-boost'
    mode: '0755'
