---
- name: download binary
  get_url:
    url: '{{ lighthouse_binary }}'
    checksum: 'sha256:{{ lighthouse_checksum }}'
    dest: '/tmp/lighthouse_binary.tar.gz'
    mode: '0700'
    #force: yes
  

- name: unarchive binary file
  unarchive:
    src: '/tmp/lighthouse_binary.tar.gz'
    dest: '/tmp/'
    mode: '0755'
    remote_src: true

- name: Copy binary
  copy:
    remote_src: true
    src: '/tmp/lighthouse'
    dest: '/home/{{ ethereum_user }}/bin/lighthouse'
    mode: '0755'
  become: true
  become_user: "{{ ethereum_user }}"
