---

- name: download erigon binary
  get_url:
    url: '{{ erigon_binary }}'
    #checksum: 'sha256:{{ erigon_checksum }}'
    dest: '/home/{{ ethereum_user }}/downloads/erigon_binary.tar.gz'
    mode: '0644'
  
- name: unarchive erigon binary file
  unarchive:
    src: '/home/{{ ethereum_user }}/downloads/erigon_binary.tar.gz'
    dest: '/home/{{ ethereum_user }}/downloads/erigon/'
    mode: '0755'
    remote_src: true

- name: Copy erigon binary
  copy:
    remote_src: true
    src: '/home/{{ ethereum_user }}/downloads/erigon/erigon'
    dest: '/home/{{ ethereum_user }}/bin/erigon'
    mode: '0755'
