---
- name: download lighthouse binary
  get_url:
    url: '{{ lighthouse_binary }}'
    checksum: 'sha256:{{ lighthouse_checksum }}'
    dest: '/home/{{ ethereum_user }}/downloads/lighthouse_binary.tar.gz'
    mode: '0644'

- name: unarchive lighthouse binary file
  unarchive:
    src: '/home/{{ ethereum_user }}/downloads/lighthouse_binary.tar.gz'
    dest: '/home/{{ ethereum_user }}/downloads/lighthouse/'
    mode: '0755'
    remote_src: true

- name: Copy lighthouse binary
  copy:
    remote_src: true
    src: '/home/{{ ethereum_user }}/downloads/lighthouse/lighthouse'
    dest: '/home/{{ ethereum_user }}/bin/lighthouse'
    mode: '0755'

