- name: Install dependencies
  import_tasks: install_dependencies.yml
  become: true

- name: Create ethereum service user
  user:
    name: "{{ ethereum_user }}"
    password: '*'   # pw is locked/disabled.  key auth only + passwordless sudo
    state: present
    shell: /bin/bash
    createhome: yes
    home: "/home/{{ ethereum_user }}"
  become: true

- name: Deploy .profile for {{ ethereum_user }}
  template:
    src: 'profile.j2'
    dest: '/home/{{ ethereum_user }}/.profile'
    owner: '{{ ethereum_user }}'
    group: '{{ ethereum_user }}'
    mode: '0600'
  become: true

#- name: Create {{ eth_data_dir }}
#  file:
#    path: "{{ eth_data_dir }}"
#    state: directory
#    mode: '0750'
#    owner: "{{ ethereum_user }}"
#    group: "{{ ethereum_user }}"
#  become: true

- name: Install golang
  import_tasks: install_golang.yml

- name: Build and install erigon from source
  import_tasks: build_and_install_erigon.yml

- name: Deploy erigon service environment file
  copy:
    src: environment.env
    dest: "/home/{{ ethereum_user }}/environment.env"
    owner: "{{ ethereum_user }}"
    group: "{{ ethereum_user }}"
    mode: '0644'
  become: true
  

- name: Deploy erigon service systemd service file
  template:
    src: erigon.service.j2
    dest: /etc/systemd/system/erigon.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Deploy erigon rpc service systemd service file
  template:
    src: erigon_rpcdaemon.service.j2
    dest: /etc/systemd/system/erigon_rpc.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Deploy erigon service helper script
  template:
    src: get_public_ip.sh.j2
    dest: "/home/{{ ethereum_user }}/get_public_ip.sh"
    owner: "{{ ethereum_user }}"
    group: "{{ ethereum_user }}"
    mode: '0755'
  become: true

#- name: Create keystore
#  import_tasks: create_keystore.yml
#  tags: "native_keystore"

- name: Enable and start erigon service
  systemd:
    name: erigon.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true

- name: Enable and start erigon rpc service
  systemd:
    name: erigon_rpc.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true

#- name: Deploy restore from snapshot script
#  import_tasks: restore_snapshot.yml
#  tags: 'restore_celo_snapshot'

#- name: Deploy generate proof of possession script
#  import_tasks: generate_pop.yml
#  tags: 'generate_pop'
