- name: Create ethereum service user
  user:
    name: "{{ ethereum_user }}"
    password: '*'   # pw is locked/disabled.  key auth only + passwordless sudo
    state: present
    shell: /bin/bash
    createhome: yes
    home: "/home/{{ ethereum_user }}"
  become: true

- name: Deploy .profile for {{ ethereum_user }}
  template:
    src: 'profile.j2'
    dest: '/home/{{ ethereum_user }}/.profile'
    owner: '{{ ethereum_user }}'
    group: '{{ ethereum_user }}'
    mode: '0600'
  become: true

- name: Create /home/{{ ethereum_user }}/bin
  file:
    path: "/home/{{ ethereum_user }}/bin"
    state: directory
    mode: '0750'
    owner: "{{ ethereum_user }}"
    group: "{{ ethereum_user }}"
  become: true

- name: Build and install erigon from source
  import_tasks: build_and_install_erigon.yml
  when: erigon_binary is not defined

- name: Install erigon binary
  import_tasks: install_erigon.yml
  when: erigon_binary is defined
  notify: restart erigon

- name: Install lighthouse binary
  import_tasks: install_lighthouse.yml
  when: lighthouse_binary is defined
  notify:
    - restart lighthouse-beacon
    - restart lighthouse-validator

- name: Install mevboost binary
  import_tasks: install_mevboost.yml
  when: mevboost_binary is defined
  notify: restart mevboost

- name: Deploy erigon service environment file
  copy:
    src: environment.env
    dest: "/home/{{ ethereum_user }}/environment.env"
    owner: "{{ ethereum_user }}"
    group: "{{ ethereum_user }}"
    mode: '0644'
  become: true
  
- name: Deploy erigon service systemd service file
  template:
    src: erigon.service.j2
    dest: /etc/systemd/system/erigon.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: restart erigon

#- name: Deploy erigon rpc service systemd service file
#  template:
#    src: erigon_rpcdaemon.service.j2
#    dest: /etc/systemd/system/erigon_rpc.service
#    owner: root
#    group: root
#    mode: '0644'
#  become: true

- name: Deploy mevboost service systemd service file
  template:
    src: mevboost.service.j2
    dest: /etc/systemd/system/mevboost.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: restart mevboost

- name: Deploy lighthouse-beacon service systemd service file
  template:
    src: lighthouse-beacon.service.j2
    dest: /etc/systemd/system/lighthouse-beacon.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: restart lighthouse-beacon

- name: Deploy lighthouse-validator service systemd service file
  template:
    src: lighthouse-validator.service.j2
    dest: /etc/systemd/system/lighthouse-validator.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: restart lighthouse-validator

- name: Deploy erigon service helper script
  template:
    src: get_public_ip.sh.j2
    dest: "/home/{{ ethereum_user }}/get_public_ip.sh"
    owner: "{{ ethereum_user }}"
    group: "{{ ethereum_user }}"
    mode: '0755'
  become: true

- name: Enable and start erigon execution client service 
  systemd:
    name: erigon.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true

- name: Enable and start mevboost service 
  systemd:
    name: mevboost.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true

- name: Enable and start lighthouse beacon service
  systemd:
    name: lighthouse-beacon.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true

- name: Enable and start lighthouse validator client service
  systemd:
    name: lighthouse-validator.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true
