# this works on hetzner AX41 and AX51 NVME SSD's configured with ZFS as proxmox root, and uses any remaining space on the disk
# for swap

- name: Show debug data
  debug: var=hostvars

- name: Install parted
  apt:
    name: parted
    state: present
    update_cache: true

- name: Read device information from first SSD
  parted: "device=/dev/nvme0n1 unit=MiB"
  register: nvme0n1_info

#- name: Debug the device info
  #debug:
    #msg: "nvme0n1_info: {{ nvme0n1_info.partitions }}"
    #msg: "nvme0n1_info.partitions[2]: {{ nvme0n1_info.partitions[2] }}"

    # "msg": "nvme0n1_info.partitions[0]: {'num': 1, 'begin': 0.02, 'end': 1.0, 'size': 0.98, 'fstype': '', 'name': '', 'flags': ['bios_grub'], 'unit': 'mib'}"
    # "msg": "nvme0n1_info.partitions[1]: {'num': 2, 'begin': 1.0, 'end': 513.0, 'size': 512.0, 'fstype': 'fat32', 'name': '', 'flags': ['boot', 'esp'], 'unit': 'mib'}"
    # "msg": "nvme0n1_info.partitions[2]: {'num': 3, 'begin': 513.0, 'end': 460800.0, 'size': 460287.0, 'fstype': 'zfs', 'name': '', 'flags': [], 'unit': 'mib'}"

- name: Partition the first SSD
  parted:
    device: /dev/nvme0n1
    fs_type: linux-swap
    label: gpt
    name: swap
    number: 4
    part_end: "100%"
    part_start: "{{ nvme0n1_info.partitions[2].end + 1}}MiB" 
    state: present

- name: Read device information from second SSD
  parted: "device=/dev/nvme0n1 unit=MiB"
  register: nvme1n1_info

- name: Partition the second SSD
  parted:
    device: /dev/nvme1n1
    fs_type: linux-swap
    label: gpt
    name: swap
    number: 4
    part_end: "100%"
    part_start: "{{ nvme1n1_info.partitions[2].end + 1}}MiB" 
    state: present

