cloudflared_package_name: cloudflared
cloudflared_state: present
cloudflared_key_url: https://pkg.cloudflare.com/cloudflare-main.gpg
cloudflared_key_path: /usr/share/keyrings/cloudflare-main.gpg
cloudflared_repo: "deb [signed-by={{ cloudflared_key_path }}] https://pkg.cloudflare.com/cloudflared any main"
cloudflared_repo_filename: cloudflared
cloudflared_ping_group_range: "0 2147483647"
