- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart cloudflared tunnels
  ansible.builtin.systemd:
    name: "cloudflared@{{ item.name }}"
    state: restarted
  loop: "{{ cloudflare_tunnels }}"
  no_log: true
