- name: Install acl via apt
# needed for running tasks as svc_user properly
# curl just because
  apt:
    name:
      - acl
      - curl
    state: present
    update_cache: yes
  become: true

- name: Create service user
  user:
    name: "{{ svc_user }}"
    password: '*'   # pw is locked/disabled.  key auth only + passwordless sudo
    state: present
    shell: /bin/bash
    createhome: yes
    home: "/home/{{ svc_user }}"
    #uid: "{{ svc_uid }}"
  become: true

- name: Deploy .profile from template
  template:
    src: profile.j2
    dest: /home/{{ svc_user }}/.profile
    owner: "{{ svc_user }}"
    group: "{{ svc_user }}"
    mode: 0600
  become: true
  become_user: "{{ svc_user }}"

- name: Ensure .config directory exists for {{ svc_user }}
  file:
    path: "/home/{{ svc_user }}/.config"
    state: directory
    owner: "{{ svc_user }}"
    group: "{{ svc_user }}"
    mode: '0755'
  become: true

- name: Build zebra from source
  include_tasks: build_zebra.yml
  when: zebra_install_type == "source"
  #vars:
  #  svc_user: "{{ svc_user }}"
  #  zebra_repo: "{{ zebra_repo }}"
  #  zebra_tag: "{{ zebra_tag }}"

- name: Deploy zebrad.service from template
  template:
    src: zebrad.service.j2
    dest: /etc/systemd/system/zebrad.service
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart zebrad

- name: Generate zebrad config
  command: "zebrad generate -o /home/{{ svc_user }}/.config/zebrad.toml"
  become: true
  become_user: "{{ svc_user }}"

- name: Enable and start zebrad
  systemd:
    name: "zebrad"
    enabled: yes
    state: started
    daemon_reload: yes
  become: true
