- name: Debug celo-proxy
  debug:
    msg: "{{ hostvars[inventory_hostname] }}"

- name: Create celo service user
  user:
    name: "{{ celo_user }}"
    password: '*'   # pw is locked/disabled.  key auth only + passwordless sudo
    state: present
    shell: /bin/bash
    createhome: yes
    home: "/home/{{ celo_user }}"
    groups:
      - docker

- name: Deploy celo-proxy service systemd service file
  template:
    src: celo-proxy.service.j2
    dest: /etc/systemd/system/celo-proxy.service
    owner: root
    group: root
    mode: '0755'
  notify: daemon-reload

- name: Create {{ celo_data_dir }}
  file:
    path: "{{ celo_data_dir }}"
    state: directory
    mode: '0750'
    owner: "{{ celo_user }}"
    group: "{{ celo_user }}"

- name: Create keystore
  import_tasks: create_keystore.yml
  tags: "keystore"

- name: Create docker network for celo-proxy
  community.docker.docker_network:
    name: celo-proxy
    driver_options: { "com.docker.network.driver.mtu": "{{ sdn_mtu }}" }

- name: Enable and start celo-proxy service
  systemd:
    name: celo-proxy.service
    enabled: yes
    state: started
    daemon_reload: yes
