- name: create /etc/vimrc.local to disable visual copy mode for all users
  copy:
    src: vimrc.local
    dest: /etc/vim/vimrc.local
    owner: root
    group: root
    mode: '0644'

- name: Disable overrides in /etc/vim/vimrc
  lineinfile:
    path: "/etc/vim/vimrc"
    regex: '^" let g:skip_defaults_vim = 1'
    line: 'let g:skip_defaults_vim = 1'
