#- name: Debug admin_users
#  debug:
#    msg: "admin_users item: {{ item }}"
#  loop: "{{ admin_users }}"

#- name: debug virtualization
#  debug:
#    msg: "ansible_virtualization_role: {{ ansible_virtualization_role }},  ansible_virtualization_tech_guest: {{ ansible_virtualization_tech_guest }}, ansible_virtualization_tech_host: {{ ansible_virtualization_tech_host }}"
#  tags: debug_virt

#- name: Show debug data
#  debug: var=hostvars

#- name: Show available facts
  #debug: var=ansible_facts
  #debug: var=ansible_facts['distribution_release']

#- name: Debug cloud_provider
#  debug:
#    msg: "cloud_provider: {{ cloud_provider }}"

- name: Deploy hosts file
  copy:
    src: etc_hosts.vault
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  tags: 'update_hosts'
  when: ansible_virtualization_role == "guest"

- name: Disable proxmox enterprise repo
  apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/pve {{ ansible_facts['distribution_release'] }} pve-enterprise
    state: absent

- name: Update and upgrade the machine
  apt:
    upgrade: dist
    update_cache: true

- name: Install needful packages
  apt:
    name:
      - screen
      - htop
      - vim
      - jq
      - sudo
    state: present

- name: Install unattended-upgrades but only on guest VM and containers
  apt:
    name:
      - unattended-upgrades
    state: present
  when: ansible_virtualization_role == "guest"

# doesn't seem to be required anymore as latest htop properly reports RAM within containers
#- name: Replace packaged htop with binary that properly supports LXC
#  import_tasks: htop.yml
#  tags: 'htop'
#  when: ansible_virtualization_role == "guest" and ansible_virtualization_type == "lxc"

- name: set SDN MTU for guest workloads
  import_tasks: set_mtu.yml
  tags: 'mtu'
  when: ansible_virtualization_role == "guest"

- name: Disable password auth for sshd
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^#PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
  notify:
    - restart sshd

- name: Create admin users
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    state: present
    shell: /bin/bash
    createhome: yes
    home: /home/{{ item.username }}
    groups:
      - sudo
      - adm
    append: yes
  loop: "{{ admin_users }}"

- name: Set authorized key for admin users
  authorized_key: 
    user: "{{ item.username }}"
    state: present
    key: "{{ item.sshpublickey }}"
    manage_dir: yes
  when: item.sshpublickey is defined
  loop: "{{ admin_users }}"

- name: Setup common aliases for admin users
  lineinfile:
    path: /home/{{ item.username }}/.profile
    line: alias ll='ls -laF'
    state: present
  loop: "{{ admin_users }}"

- name: Setup common aliases for root user
  lineinfile:
    path: /root/.profile
    line: alias ll='ls -laF'
    state: present

- name: Setup screenrc for all users
  copy:
    src: 'screenrc'
    dest: '/etc/screenrc'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Setup passwordless sudo for members of sudo group
  lineinfile: 
    path: /etc/sudoers
    regexp: '%sudo	ALL=(ALL:ALL) ALL'
    line: '%sudo	ALL=(ALL:ALL) NOPASSWD:ALL' 

- name: Configure vim to disable visual mouse and a few other tweaks
  import_tasks: configure_vim.yml

# this this has been resolved in latest d12 template
# Debian 12 (bullseye) has systemd-networkd-wait-online.service enabled by default
# but it doesn't work properly in Proxmox LXC's because networking isn't configured 
# via systemd, so it will time out and cause the boot to hang for 2 minutes.
#- name: Mask systemd-networkd-wait-online on Debian 12
#  systemd:
#    name: systemd-networkd-wait-online.service
#    masked: true
#  when: ansible_facts['distribution_release'] == "bookworm"

# disable ipv6
- name: Disable ipv6
  import_tasks: disable_ipv6.yml
  tags: "disable_ipv6"
