- name: Create take_snapshot script
  template:
    src: take_snapshot.sh.j2
    dest: /home/{{ celo_user }}/take_snapshot.sh
    owner: "{{ celo_user }}"
    group: "{{ celo_user }}"
    mode: 0750
  become: true

- name: Update sudoers to permit {{ celo_user }} to start/stop celo-geth service
  community.general.sudoers:
    name: allow-celo-geth-start-stop
    state: present
    user: "{{ celo_user }}"
    commands: /bin/systemctl stop celo-geth,/bin/systemctl start celo-geth
  become: true

- name: Create take snapshot cronjob    # careful with this, as this will stop the daemon to take the snapshot. do NOT run this on validators!
  cron:
    user: '{{ celo_user }}'
    name: '{{ network }} snapshot'
    minute: '{{ snapshot_minute }}'
    hour: '{{ snapshot_hour }}'
    job: '/bin/bash /home/{{ celo_user }}/take_snapshot.sh | logger'
  when: (schedule_snapshots is defined and schedule_snapshots|bool == true )
  become: true
