- name: Create user 
  user:
    name: "{{ user_to_create }}"
    password: '*'   # pw is locked/disabled.  key auth only + passwordless sudo
    state: present
    shell: /usr/bin/bash
    createhome: yes
    home: /home/{{ user_to_create }}
    groups:
      - sudo

- name: Set authorized key for created user
  authorized_key: 
    user: "{{ user_to_create }}"
    state: present
    key: "{{ authorized_key }}"
    manage_dir: yes

- name: Setup common aliases for created user
  lineinfile:
    path: /home/{{ user_to_create }}/.profile
    line: alias ll='ls -laF'
    state: present

- name: Setup common aliases for root user
  lineinfile:
    path: /root/.profile
    line: alias ll='ls -laF'
    state: present

- name: Copy restart_services.sh helper script to home dir
  copy:
    src: restart_pve_services.sh
    dest: "/home/{{ user_to_create }}/restart_pve_services.sh"
    owner: "{{ user_to_create }}"
    group: "{{ user_to_create }}"
    mode: '0740'

- name: Configure vim
  import_tasks: vim.yml
