svc_user: "ghost"
ghost_gid: 1111
ghost_uid: 1111
ghost_group: "ghost"
ghost_sites:
  - icanhazip:
    hostname: "icanhazip.com"
    port: 3000
  - youthinasia:
    hostname: "youthinasia.com"
    port: 3001
  - silentlucidity:
    hostname: "silentlucidity.com"
    port: 3002

# r2 specific variables
r2_access_key_id: "{{ vault_r2_access_key_id }}"
r2_secret_access_key: "{{ vault_r2_secret_access_key }}"
r2_endpoint: "{{ vault_r2_endpoint }}"
