svc_user: "ghost"
ghost_image: "ghost:5-alpine"
ghost_gid: 1111
ghost_uid: 1111
ghost_group: "ghost"
# example of ghost_sites
#ghost_sites:
#  - icanhazip:
#    hostname: "icanhazip.com"
#    port: 3000
#  - youthinasia:
#    hostname: "youthinasia.com"
#    port: 3001
#  - silentlucidity:
#    hostname: "silentlucidity.com"
#    port: 3002

# r2 specific variables
r2_access_key_id: "{{ vault_ghost_r2_access_key_id }}"
r2_secret_access_key: "{{ vault_ghost_r2_secret_access_key }}"
r2_endpoint: "{{ vault_ghost_r2_endpoint }}"
backup_bucket_name: "{{ vault_ghost_backup_bucket_name }}"

snapshot_method: "rsync"
storage_backends:
  - "r2"

ghost_discord_webhook: "{{ vault_ghost_discord_webhook }}"

# run the snapshot script at 4:04am on the 4th day of the week
snapshot_minute: 04
snapshot_hour: 04
snapshot_day: 04
schedule_snapshots: true

