- name: restart zebrad
  systemd:
    name: zebrad
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: true

- name: restart lightwalletd
  systemd:
    name: lightwalletd
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: true

- name: restart zaino
  systemd:
    name: zaino
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: true
