- name: Restart stacks-node
  systemd:
    name: stacks-node
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: true

- name: Restart stacks-signer
  systemd:
    name: stacks-signer
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: true
