- name: restart stacks-node
  systemd:
    name: stacks-node
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: true

- name: restart stacks-signer
  systemd:
    name: stacks-signer
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: true

- name: start netfilter-persistent
  systemd: 
    name: netfilter-persistent
    state: started
    enabled: yes
    daemon_reload: yes
  become: true

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: true
