- name: Restart udev
  systemd:
    name: udev
    state: restarted
    enabled: yes

- name: restart networking (ifupdown-safe)
  include_tasks: handler_restart_networking.yml

- name: Reload nftables
  ansible.builtin.systemd:
    name: nftables
    state: reloaded
  become: true
