- name: Install dependencies
  apt:
    name: 
     - ca-certificates 
     - curl 
     - gnupg 
     - lsb-release
     - jq
     - fuse-overlayfs # required for docker on LXC
     - acl            # required for ansible to become unpriv'd user to run tasks successfully
    state: present
    update_cache: true

- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repository to apt
  apt_repository:
    filename: docker 
    #repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bullseye stable
    repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
    state: present
    
- name: Install docker engine
  apt:
    name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    state: present
    update_cache: true
  
- name: Configure docker daemon
  template:
    src: docker_daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: restart docker

- name: Restart docker to enable fuse overlayfs
  service:
    name: docker
    state: restarted
  
- name: Add admin users to docker group
  user:
    name: "{{ item.username }}"
    groups: docker
    append: yes
  loop: "{{ admin_users }}"

- name: Install docker-compose
  import_tasks: compose.yml
  tags: docker_compose
- name: Install packages required for ansible to interact w/ python on host
  apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: false
 
- name: Install required python packages for ansible to interact w/ docker on host
  pip:
    name:
      - docker
      - docker-compose
    state: present
