- name: Install dependencies
  apt:
    name: 
     - ca-certificates 
     - curl 
     - gnupg 
     - lsb-release
     - jq
     - acl            # required for ansible to become unpriv'd user to run tasks successfully
    state: present
    update_cache: true

# trying docker and ZFS *without* fuse-overlayfs for now, which is reported to work on 6.x kernels
# https://forum.proxmox.com/threads/unprivileged-lxc-container-eventually-locks-up-pve-host-processes.108362/#post-506058
# https://forum.proxmox.com/threads/lxc-zfs-docker-overlay2-driver.122621/
#- name: Install dependencies for docker on LXC on ZFS
#  apt:
#    name:
#     - fuse-overlayfs # required for docker on LXC.  note: may cause problems w/ underlying ZFS and replication/snapshots
#    state: present
#  when: ansible_virtualization_role == "guest" and ansible_virtualization_type == "lxc"

- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repository to apt
  apt_repository:
    filename: docker 
    #repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bullseye stable
    repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
    state: present
    
- name: Install docker engine
  apt:
    name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    state: present
    update_cache: true

# as of Docker version 23.0.0, build e92dd87 /etc/docker is no longer created by installing the debian package
- name: Ensure /etc/docker exists
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure docker daemon
  template:
    src: docker_daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: restart docker
  
- name: Add admin users to docker group
  user:
    name: "{{ item.username }}"
    groups: docker
    append: yes
  loop: "{{ admin_users }}"

- name: Install docker-compose
  import_tasks: compose.yml
  tags: docker_compose
- name: Install packages required for ansible to interact w/ python on host
  apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: false
 
# not working on debian12 yet
#- name: Install required python packages for ansible to interact w/ docker on host
#  pip:
#    name:
#      - docker
#      - docker-compose
#    state: present
