- name: Install rclone
  become: true
  apt:
    name:
      - rclone
    state: present
    update_cache: yes

- name: Create rclone config directory
  file:
    path: "/home/{{ svc_user }}/{{ item }}"
    state: directory
    mode: '0750'
    owner: "{{ svc_user }}"
    group: "{{ svc_user }}"
  become: true
  loop:
    - ".config"
    - ".config/rclone"

- name: Deploy rclone config file
  template:
    src: 'rclone.conf.j2'
    dest: '/home/{{ svc_user }}/.config/rclone/rclone.conf'
    owner: '{{ svc_user }}'
    group: '{{ svc_user }}'
    mode: '0600'
  become: true

