- name: Install from source
  block:
    - name: Clone celo-blockchain repo
      git:
        repo: '{{ celo_repo }}'
        dest: '/home/{{ celo_user }}/celo-blockchain'
        version: '{{ celo_version }}'
        update: yes
        force: yes
        depth: 1
      become: true
      become_user: "{{ celo_user }}"

    - name: Build and install celo geth
      command: '{{ item }}'
      args:
        chdir: '/home/{{ celo_user }}/celo-blockchain'
      with_items:
        - 'make geth'
      environment:
        PATH: '{{ path }}'
        GOPATH: '/home/{{ celo_user }}/go'
      become: true
      become_user: "{{ celo_user }}"

- name: Install geth binary
  block:
    - name: Create go/bin directory
      file:
        path: "/home/{{ celo_user }}/go/bin"
        state: directory
        owner: "{{ celo_user }}"
        group: "{{ celo_user }}"
        mode: '0755'
      become: true

    - name: Copy built geth binary to go/bin
      copy:
        src: "/home/{{ celo_user }}/celo-blockchain/build/bin/geth"
        remote_src: yes
        dest: "/home/{{ celo_user }}/go/bin/geth"
        owner: "{{ celo_user }}"
        mode: '0755'
      become: true
