- name: install apt packages
  apt:
    name:
      - make
      - build-essential
      - gcc
      - git
      - jq
      - curl
      - acl   # required for become_user != root
      - lz4
    state: present
    update_cache: yes
