- name: Deploy keystore generation script
  template:
    src: generate_keystore.sh.j2
    dest: "/home/{{ celo_user }}/generate_keystore.sh"
    owner: "{{ celo_user }}"
    group: "{{ celo_user }}"
    mode: '0750'

- name: Write keystore privkey to file
  shell: "echo {{ proxy_account_key }} > {{ celo_data_dir }}/proxy_account_key"

- name: Set perms on privkey file
  shell: chmod 600 {{ celo_data_dir }}/proxy_account_key && chown {{ celo_user }}:{{ celo_user }} {{ celo_data_dir }}/proxy_account_key

- name: Write keystore password to file
  shell: "echo {{ proxy_account_password }} > {{ celo_data_dir }}/proxy_account_password"

- name: Set perms on privkey file
  shell: chmod 600 {{ celo_data_dir }}/proxy_account_password && chown {{ celo_user }}:{{ celo_user }} {{ celo_data_dir }}/proxy_account_password

- name: Generate keystore
  command: "/home/{{ celo_user }}/generate_keystore.sh"
  become: true
  become_user: "{{ celo_user }}"

- name: Remove artifacts used to generate keystore
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ celo_data_dir }}/proxy_account_key"
    #- "{{ celo_data_dir }}/proxy_account_password"  # password is required to start geth so remains on the fs

- name: Copy keystore to baklava dir when running on baklava testnet
  copy:
    src: "{{ celo_data_dir }}/keystore"
    dest: "{{ celo_data_dir }}/baklava/"
    remote_src: yes
  when: network is defined and network == 'baklava'
  