- name: Create bitwarden group
  ansible.builtin.group:
    name: bitwarden
    state: present
    gid: "{{ bitwarden_gid }}"

- name: Create bitwarden service user
  user: 
    name: "bitwarden"
    password: '*'   # pw is locked/disabled.  key auth only + passwordless sudo
    state: present
    shell: /bin/bash
    createhome: yes
    home: "/home/bitwarden"
    uid: "{{ bitwarden_uid }}"
    group: "{{ bitwarden_group }}"
    groups:
      - docker
    append: true

- name: Deploy .profile for bitwarden user
  template:
    src: 'profile.j2'
    dest: '/home/bitwarden/.profile'
    owner: 'bitwarden'
    group: 'bitwarden'
    mode: '0600'
  become: true

- name: Deploy bitwarden service systemd service file
  template:
    src: bitwarden.service.j2
    dest: /etc/systemd/system/bitwarden.service
    owner: root
    group: root
    mode: '0755'
  notify: restart bitwarden

- name: Create bitwarden data dir
  file:
    path: "/home/bitwarden/bw-data"
    state: directory
    mode: '0750'
    owner: "bitwarden"
    group: "bitwarden"

- name: Create docker network for bitwarden
  community.docker.docker_network:
    name: bitwarden
    driver_options: { "com.docker.network.driver.mtu": "{{ sdn_mtu }}" }

- name: Enable and start bitwarden service
  systemd:
    name: bitwarden.service
    enabled: yes
    state: started
    daemon_reload: yes

- name: Install and configure backups for bitwarden data
  import_tasks: bitwarden_backup.yml
  tags: 'bitwarden_backup'
