- name: Debug ghost_sites
  debug:
    msg: "sites item: {{ item }}"
  loop: "{{ ghost_sites }}"

- name: Create ghost group
  ansible.builtin.group:
    name: ghost
    state: present
    gid: "{{ ghost_gid }}"

- name: Create ghost service user
  user: 
    name: "{{ svc_user }}"
    password: '*'   # pw is locked/disabled.  key auth only + passwordless sudo
    state: present
    shell: /bin/bash
    createhome: yes
    home: "/home/{{ svc_user }}"
    uid: "{{ ghost_uid }}"
    group: "{{ ghost_group }}"
    groups:
      - docker
    append: true

- name: Deploy ghost service systemd service files
  template:
    src: ghost.service.j2
    dest: "/etc/systemd/system/ghost-{{ item.hostname }}.service"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ ghost_sites }}"

- name: Create ghost data directories
  file:
    path: "/home/{{ svc_user }}/{{ item.hostname }}"
    state: directory
    mode: '0750'
    owner: "{{ svc_user }}"
    group: "{{ svc_user }}"
  loop: "{{ ghost_sites }}"

- name: Create docker network for ghost
  community.docker.docker_network:
    name: ghost
    driver_options: { "com.docker.network.driver.mtu": "{{ sdn_mtu }}" }

- name: Enable and start ghost service
  systemd:
    name: ghost-{{ item.hostname }}.service
    enabled: yes
    state: started
    daemon_reload: yes
  loop: "{{ ghost_sites }}"

- name: Include install rclone
  include_tasks:
    file: roles/common/tasks/install_rclone.yml

- name: Enable snapshot backups of ghost site content
  import_tasks: take_snapshot.yml

  