svc_user: "stacks"
# `npx stacks make_keychain` to generate the keys

stacks_testnet_private_key: "{{ vault_stacks_testnet_private_key }}"
stacks_mainnet_private_key: "{{ vault_stacks_mainnet_private_key }}"
stacks_mainnet_public_key: "{{ vault_stacks_mainnet_public_key }}"
stacks_http_auth_token: "{{ vault_stacks_http_auth_token }}"
stacks_local_peer_seed: "{{ vault_stacks_local_peer_seed }}"
stacks_testnet_pox_address: "{{ vault_stacks_testnet_pox_address }}"
stacks_mainnet_pox_address: "{{ vault_stacks_mainnet_pox_address }}"
# the p2p public address autodiscovery doesn't seem reliable, so we hard code it here
# this is used in the node-config.toml.j2 template
stacks_mainnet_p2p_address: "{{ vault_stacks_mainnet_p2p_address }}"

stacks_repo: "https://github.com/stacks-network/stacks-core"
#stacks_version: "2.5.0.0.0-rc1"
#stacks_version: "2.5.0.0.0-rc2"
#stacks_version: "2.5.0.0.0-rc3"
#stacks_version: "2.5.0.0.0-rc5"
#stacks_version: "2.5.0.0.2"
#stacks_version: "2.5.0.0.3"
#stacks_version: "2.5.0.0.4"
#stacks_version: "2.5.0.0.5"
#stacks_version: "2.5.0.0.6"
#stacks_node_version: "2.5.0.0.4"
#stacks_node_version: "2.5.0.0.7"
stacks_node_version: "3.0.0.0.0"
#stacks_signer_version: "2.5.0.0.5"
#stacks_signer_version: "signer-2.5.0.0.5.2"
stacks_signer_version: "3.0.0.0.0"
stacks_network: "mainnet"

yarn_repo_key_url: "https://dl.yarnpkg.com/debian/pubkey.gpg" 
nodesource_repo_key_url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
nodejs_version: "node_20.x"

install_type: "binary"
#install_type: "source"
