- name: Install unbound package via apt
  apt:
    name: unbound
    state: present
    update_cache: yes
  become: true

- name: Deploy unbound.conf from template
  template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf.d/dnsovertls.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - restart unbound

