svc_user: "zcash"
svc_uid: 1004
zebra_install_type: "source"
#zebra_install_type: "docker"
zebra_repo: "https://github.com/ZcashFoundation/zebra"
zebra_tag: "v2.0.1"
zebra_network: "mainnet"
zebra_listen_addr: "0.0.0.0"
zebra_listen_port: 8233
zebra_rpc_addr: "127.0.0.1"
zebra_rpc_port: 8232
metrics_endpoint_addr: "0.0.0.0"
metrics_endpoint_port: 9999
zebra_max_peers: 5

