- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name:
      - gpg
      - ca-certificates
      - curl
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure keyrings directory exists
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: "0755"

- name: Download Cloudflare GPG key
  ansible.builtin.get_url:
    url: "{{ cloudflared_key_url }}"
    dest: "{{ cloudflared_key_path }}"
    mode: "0644"
    validate_certs: yes

- name: Add Cloudflare APT repository for cloudflared
  ansible.builtin.apt_repository:
    repo: "{{ cloudflared_repo }}"
    filename: "{{ cloudflared_repo_filename }}"
    state: present

- name: Install cloudflared
  ansible.builtin.apt:
    name: "{{ cloudflared_package_name }}"
    state: "{{ cloudflared_state }}"
    update_cache: yes
    cache_valid_time: 3600



- name: Stop and disable legacy cloudflared service
  ansible.builtin.systemd:
    name: cloudflared
    state: stopped
    enabled: no
  ignore_errors: true
  failed_when: false

- name: Create the systemd template file
  ansible.builtin.template:
    src: cloudflared@.service.j2
    dest: /etc/systemd/system/cloudflared@.service
    mode: '0644'
  notify: daemon-reload

- name: Create environment files for each tunnel
  ansible.builtin.copy:
    dest: "/etc/default/cloudflared-{{ item.name }}"
    content: "TUNNEL_TOKEN={{ item.token }}"
    mode: '0600'
    owner: root
  loop: "{{ cloudflare_tunnels }}"
  notify: "Restart cloudflared tunnels"
  no_log: true

- name: Ensure all tunnels are enabled and started
  ansible.builtin.systemd:
    name: "cloudflared@{{ item.name }}"
    enabled: yes
    state: started
  loop: "{{ cloudflare_tunnels }}"
  no_log: true
